# Generated by Django 5.2.7 on 2025-11-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="all_time_coins_earned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="all_time_habits_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="all_time_hours_studied",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="all_time_tasks_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="highest_level_ever",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longest_daily_streak",
            field=models.IntegerField(default=0),
        ),
    ]
