# Generated by Django 5.2.7 on 2025-12-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_all_time_coins_earned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="coins_earned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="xp_earned",
            field=models.IntegerField(default=0),
        ),
    ]
