# Generated by Django 5.2.7 on 2025-12-26 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tasklog_coins_earned_tasklog_xp_earned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.CreateModel(
            name="SubjectColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=7)),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "year", "month"],
                        name="core_subjec_user_id_7a36c7_idx",
                    )
                ],
                "unique_together": {("user", "subject", "year", "month")},
            },
        ),
    ]
