# Generated by Django 5.2.7 on 2026-01-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_levellog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_background_color",
            field=models.CharField(
                blank=True, default="#d8b9b9", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_character",
            field=models.CharField(
                blank=True, default="default_girl", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_clothes",
            field=models.CharField(
                blank=True, default="default", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_floor_color",
            field=models.CharField(
                blank=True, default="#d8aeae", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_pants",
            field=models.CharField(
                blank=True, default="default", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_shirt",
            field=models.CharField(
                blank=True, default="default", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_shoes",
            field=models.CharField(
                blank=True, default="default", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_socks",
            field=models.CharField(
                blank=True, default="default", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="purchased_backgrounds",
            field=models.TextField(blank=True, null=True),
        ),
    ]
