# Generated by Django 5.2.7 on 2026-01-04 00:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_shopitem_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]

